### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Sunderw3k** [TruncatedDinosour/TruncatedDinosour#4]
Theres no `v` in `activity`

**Comment by Sunderw3k** [comment]
![image](https://github.com/TruncatedDinosour/TruncatedDinosour/assets/73128678/2dc0eef5-823c-4b3e-a211-a6fad834ff51)

**Comment by TruncatedDinosour** [comment]
ye sry babes im stupid i wrote that at probs like 5 am xD
ty tho :*
